public class insertRecordDocumentTYPE {
    public static void insertRecord(){
        /*List<DocumentType__c> d = new List<DocumentType__c>{
            new DocumentType__c(Name = 'Documentazione pre-contrattuale', Document_Block__c = 'f'),
            new DocumentType__c(Name = 'Documentazione pre-contrattuale', Document_Block__c = 'f')};
            
            
            insert d;
            */
            
    }
  
}